export {
  HIGH_PUNCTUATION_RULES,
  IMPRIMERIE_NATIONALE_PUNCTUATION_RULES,
  SAFE_PUNCTUATION_RULES,
  SPACE_AFTER_COMMA_RULE,
} from "./punctuation.ts";
export {
  DIGIT_GROUPING_RULE,
  EURO_SPACING_RULE,
  PERCENTAGE_SPACING_RULE,
  UNIT_SPACING_RULE,
} from "./numeric.ts";
export { ELLIPSIS_RECOGNITION_RULE, ETC_ELLIPSIS_RULE } from "./ellipsis.ts";
export { FRENCH_GUILLEMETS_SPACING_RULE } from "./quotes.ts";
export { IMPRIMERIE_NATIONALE_RULES } from "./presets.ts";
